title: Fürestveil University
description: Welcome to Fürestveil University - A 1000-year-old university set in an ancient castle deep in the heart of Fürestveil Woods. Set to the tone of dark fantasy, with notes of dark academia and gothic horror.
theme: just-the-docs

url: https://furestveil.com

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/logo.png"

color_scheme: dark_custom

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts:
  statblock:
    color: green
    opacity: 0.01
